global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using SurvayBucketsApi;
global using SurvayBucketsApi.services;
global using SurvayBucketsApi.Contracts.Polls;
global using SurvayBucketsApi.ContractMapping;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Authorization;
global using Mapster;
global using MapsterMapper;
global using SharpGrip.FluentValidation.AutoValidation.Mvc.Extensions;
global using SurvayBucketsApi.Persistence;
using SurvayBucketsApi.Errors;
